// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1dxATY_djR9pCbRzSQ0RlFKQ_nikS3zg',
    appId: '1:408591862653:web:a10d57b53ad36442d21a14',
    messagingSenderId: '408591862653',
    projectId: 'coffee-shop-db63c',
    authDomain: 'coffee-shop-db63c.firebaseapp.com',
    storageBucket: 'coffee-shop-db63c.appspot.com',
    measurementId: 'G-Z4RK0TT9CN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO4j0NuLnSizmK0X0JW2fniaNwjv5LdKI',
    appId: '1:408591862653:android:3a3d8002a6110ccbd21a14',
    messagingSenderId: '408591862653',
    projectId: 'coffee-shop-db63c',
    storageBucket: 'coffee-shop-db63c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOV4vGPQO2KDvnRirC1wDQJsnHAomfVcw',
    appId: '1:408591862653:ios:bb3b1ff5d5497051d21a14',
    messagingSenderId: '408591862653',
    projectId: 'coffee-shop-db63c',
    storageBucket: 'coffee-shop-db63c.appspot.com',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOV4vGPQO2KDvnRirC1wDQJsnHAomfVcw',
    appId: '1:408591862653:ios:91e2590f11da0224d21a14',
    messagingSenderId: '408591862653',
    projectId: 'coffee-shop-db63c',
    storageBucket: 'coffee-shop-db63c.appspot.com',
    iosBundleId: 'com.example.coffeeShop.RunnerTests',
  );
}
